    server {
 	server_name  daktoinc.co.uk;

        listen 443 ssl;
        listen [::]:443 ssl;
        ssl_certificate /etc/cloudflare/pem;
        ssl_certificate_key /etc/cloudflare/key;
        #charset koi8-r;

        #access_log  logs/host.access.log  main;





        location / {
        root   /var/lib/daksite/poc;
	   add_before_body /nav.html;
    add_after_body  /footer.html;
            index  index.html;
        }

        	
	error_page  404              /404/hack.html;

        location = /favicon.ico {
            alias /var/lib/daksite/poc/dki-1.ico;
        }

        location /disexport {
            alias /var/lib/daksite/discord;
            index index.html;
        }

        location /reddit {
            return 301 'https://www.reddit.com/r/daktoinc/';
        }


        location /.git {
		return 404;
        }

	location /matrix {
		return 301 'https://matrix.to/#/#dakto-inc:daktoinc.co.uk';
	}

	location /discord {
		return 301 'https://discord.com/invite/XHyzzA3rmz';
	}

	location /.well-known/matrix/client {
    return 200 '{"m.homeserver": {"base_url": "https://matrix.daktoinc.co.uk"}}';
    default_type application/json;
    add_header Access-Control-Allow-Origin *;
}

    location /.well-known/matrix/server {
        return 200 '{"m.server": "matrix.daktoinc.co.uk"}';
        default_type application/json;
    }

}
