server {
 	 server_name  new.daktoinc.co.uk;

        listen 443 ssl;
        listen [::]:443 ssl;
        ssl_certificate /etc/cloudflare/pem;
        ssl_certificate_key /etc/cloudflare/key;
        #charset koi8-r;

        #access_log  logs/host.access.log  main;


	location / {
	return 301 https://daktoinc.co.uk/;
	}


    }


